"""
Django settings for TheFarm project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""


from pathlib import Path
import os
import dj_database_url
import django_heroku
import environ


from .logging_helpers import *

# from . import get_env_value

root = environ.Path(__file__) - 3  # get root of the project

# Initialise environment variables
env = environ.Env()
environ.Env.read_env()  # reading .env file


SITE_ROOT = root()


# CACHES = {'default': env.cache('REDIS_CACHE_URL')}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
# BASE_DIRZ = os.path.dirname(os.path.dirname(
#     os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = ")x2v*^r!2im9!qga+$ml-m2ne2tgmqy#r*-%1m3ob0)bluy$yathiswashowwedidthefirstproject2020"
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY', 'm9!qga+$ml)x2v*^r!2i-mThebearingbesoright@1$8obt2_+&k3q+pmu)598sj6yjpkag')
# SECRET_KEY = os.environ['SECRET_KEY']
# SECRET_KEY = env('SECRET_KEY')
# SECRET_KEY = env.str('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
# DEBUG = os.environ.get('DJANGO_DEBUG', '') != 'False'
# DEBUG = env.bool('DEBUG', default=False)
TEMPLATE_DEBUG = DEBUG


ALLOWED_HOSTS = [".herokuapp.com", "127.0.0.1", ]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    'whitenoise.runserver_nostatic',
    "django.contrib.staticfiles",
    "accounts.apps.AccountsConfig",
    "django_filters",
    "crispy_forms",
    "tempus_dominus",
    "annoying",
]


CRISPY_TEMPLATE_PACK = "bootstrap4"


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'rollbar.contrib.django.middleware.RollbarNotifierMiddleware',
]

ROOT_URLCONF = "TheFarm.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "TheFarm.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'FARMLAND',
    #     'USER': '*****',
    #     'PASSWORD': '******',
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    # }
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.environ['DATABASE_NAME'],
#         'HOST': os.environ['DATABASE_HOST'],
#         'PORT': int(os.environ['DATABASE_PORT']),
#     }
# }

# DATABASES = {
#     'default': env.db('DATABASE_URL')
#     }

# Heroku: Update database configuration from $DATABASE_URL.
db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# The absolute path to the directory where collectstatic will collect static files for deployment.
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# STATIC_ROOT = "/var/www/example.com/static/"

# The URL to use when referring to static files (where they will be served from)
STATIC_URL = "/static/"

# Additional locations where static files may exist
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]


MEDIA_URL = '/images/'
MEDIA_ROOT = os.path.join(BASE_DIR, "/static/images")

# variable to set the use of whitenoise compression as the file storage engine
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Configuration in relation to the environment variable

# public_root = root.path('public/')
# MEDIA_ROOT = public_root('media')
# MEDIA_URL = env.str('MEDIA_URL', default='media/')
# STATIC_ROOT = public_root('static')
# STATIC_URL = env.str('STATIC_URL', default='static/')


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Email SMTP Configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "royalttynation@gmail.com"
EMAIL_HOST_PASSWORD = "PASSWORD"
# EMAIL_USE_SSL = False

ADMINS = [('DJ1', 'royalttynation@gmail.com'), ]


# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,

#     'root': {
#         'level': 'WARNING',
#         'handlers': ['all_file'],
#     },

#     'loggers': {
#         'django': {
#             'handlers': ['fileDEBUG', 'fileINFO'],
#             'propagate': True,
#             'level': 'DEBUG',
#         },
#         'django.server': {
#             'handlers': ['django_all'],
#             'level': 'INFO',
#         },
#         'django.request': {
#             'handlers': ['django_all'],
#             'level': 'INFO',
#         },
#         'django.db.backends': {
#             'handlers': ['django_all'],
#             'level': 'DEBUG',
#         }
#     },

#     'handlers': {
#         'fileDEBUG': {
#             'level': 'DEBUG',
#             'class': 'logging.FileHandler',
#             'filename': './logs/debug.log',
#             'formatter': 'simpleRe',
#         },
#         'fileINFO': {
#             'level': 'INFO',
#             'class': 'logging.FileHandler',
#             'filename': './logs/debugINFO.log',
#             'formatter': 'simpleReINFO',
#         },
#         'django_all': {
#             # 'level': 'INFO',
#             'class': 'logging.FileHandler',
#             'filename': './logs/django.log',
#             # 'formatter': 'simpleReINFO',
#         },
#         'django_all': {
#             # 'level': 'INFO',
#             'class': 'logging.FileHandler',
#             'filename': './logs/djangofunc.log',
#             'formatter': 'funct_formatter',
#         },
#         'all_file': {
#             # 'level': 'INFO',
#             'class': 'logging.FileHandler',
#             'filename': './logs/rootlogs.log',
#             'formatter': 'funct_formatter',
#         },
#     },

#     'formatters': {
#         'simpleRe': {
#             'format': '{levelname} {message}',
#             'style': '{',
#         },
#         'simpleReINFO': {
#             'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
#             'style': '{',
#         },
#         'funct_formatter': {
#             'format': '[{pathname}:{funcName}:{lineno:d}] {message}',
#             'style': '{',
#         },
#     },
# }

ROLLBAR = {
    'access_token': 'f823d023f94d4712b7c5f858d33cf7b9',
    'environment': 'development' if DEBUG else 'production',
    'branch': 'master',
    'root': os.getcwd(),
}


CONSOLE_LOGGING_FORMAT = '%(hostname)s %(asctime)s %(levelname)-8s %(threadName)-14s' \
    '(%(pathname)s:%(lineno)d) %(name)s.%(funcName)s: %(message)s'
CONFIG_FILE = os.path.dirname(__file__)
CONSOLE_LOGGING_FILE_LOCATION = os.path.join(CONFIG_FILE.split(
    f'config(os.sep)settings')[0], 'django-wrds.log')
# FORMAT = '%(hostname)s %(asctime)s %(levelname)-8s' \
#     '%(threadName)-14s (%(pathname)s:%(lineno)d) ' \
#     '%(name)s.%(funcName)s: %(message)s'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'loggers': {
        # Root logger
        '': {
            'level': os.getenv('ROOT_LOG_LEVEL', 'INFO'),
            'handlers': ['file', 'rollbar'],
        },
        'django': {
            # The 'django' logger is configured by Django out of the box. Here, it is reconfigured in order to
            # utilize the file logger and allow configuration at runtime
            'handlers': ['mail_admins', 'file', 'rollbar'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.server': {
            'propagate': True,
        },
        'django.http': {
            'propagate': False,
            'level': 'DEBUG',
            'handlers': ['file', 'rollbar'],
        },
        'django.db.backends': {
            'level': 'DEBUG',
            'handlers': ['file'],
        },
        'django.security.DisallowedHost': {
            'level': 'ERROR',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file'],
            'level': 'ERROR',
            # 'propagate': True,
        },
    },
    'formatters': {
        'my_formatter': {
            'format': CONSOLE_LOGGING_FORMAT,
            'style': '%',
            'class': 'TheFarm.settings.logging_helpers.HostnameAddingFormatter'
        }
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false', 'ígnore_something'],
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'my_formatter',
        },
        'rollbar': {
            'level': 'WARNING',
            'filters': ['require_debug_false'],
            'access_token': 'f823d023f94d4712b7c5f858d33cf7b9',
            'environment': 'production',
            'class': 'rollbar.logger.RollbarHandler'
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': CONSOLE_LOGGING_FILE_LOCATION,
            'mode': 'a',
            'encoding': 'utf-8',
            'formatter': 'my_formatter',
            'backupCount': 5,
            'maxBytes': 10485760,
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'ignore_something': {
            '()': 'mysite.logging_helpers.SomethingFilter',
        },
    },
}

# Setting default protocol
# ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"

# HSTP configuration for http and https
# SECURE_HSTS_SECONDS = None

# SECURE_HSTS_INCLUDE_SUBDOMAINS = False

# SECURE_HSTS_PRELOAD = False

# SECURE_CONTENT_TYPE_NOSNIFF = False
# SECURE_BROWSER_XSS_FILTER = False
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SECURE_PROXY_SSL_HEADER = None

# CSRF_TRUSTED_ORIGINS = ['https://morning-chamber-13981.herokuapp.com/']

# SSL redirect to https configuration
# SECURE_SSL_REDIRECT = False

# CSRF configuration
# CSRF_COOKIE_SECURE = False

# Session configuration
# SESSION_COOKIE_SECURE = False

# CORS_REPLACE_HTTPS_REFERER = False

# HOST_SCHEME = "http://"

# SECURE_FRAME_DENY = False


# Configuration for Django and Heroku
django_heroku.settings(locals())

ADMINS = [('JT', 'royalttynation@gmail.com')]

# # Specify the default test runner.
# TEST_RUNNER = 'django.test.runner.DiscoverRunner'

# # Import the local settings for the current machine
# try:
#     from djangocon.local_settings import *
# except Exception, e:
# 	pass
#     # logging.debug("local_settings not found or contains errors(%s). Skipping local_settings.. " % e)
