# Generated by Django 3.2.8 on 2021-11-08 04:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customer_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brooder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brooder_ID', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('is_occupied', models.BooleanField(default=False, null=True)),
                ('last_cleaning_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flock_breedtype', models.CharField(choices=[('Broiler', 'Broiler'), ('Layers', 'Layers')], max_length=200, null=True)),
                ('batch_no', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('flock_quantity', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('date_flock_bought', models.DateTimeField(auto_now_add=True, null=True)),
                ('flock_price', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1.0)])),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_quantity',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
