# Generated by Django 3.2.8 on 2021-11-08 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeds_type', models.CharField(choices=[('Layers Mash', 'Layers Mash'), ('Broilers Mash', 'Broilers Mash'), ('Starter', 'Starter'), ('Finisher', 'Finisher')], max_length=200, null=True)),
                ('feed_name', models.CharField(max_length=200, null=True)),
                ('date_feed_bought', models.DateField(null=True)),
                ('feed_quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200, null=True)),
                ('date_med_bought', models.DateField(null=True)),
                ('last_used', models.DateField(null=True)),
                ('expiry_date', models.DateField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='brooder',
            name='brooder_ID',
        ),
        migrations.AddField(
            model_name='brooder',
            name='brooder_breed',
            field=models.CharField(choices=[('Broiler', 'Broiler'), ('Layers', 'Layers')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='brooder',
            name='flock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.flock'),
        ),
        migrations.AddField(
            model_name='flock',
            name='is_closed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_cost', models.FloatField(null=True)),
                ('sale_date', models.DateField(auto_now_add=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.order')),
            ],
        ),
        migrations.CreateModel(
            name='Mortality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mortality_count', models.FloatField(null=True)),
                ('mortality_date', models.DateField(auto_now_add=True, null=True)),
                ('brooder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.brooder')),
                ('flock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.flock')),
            ],
        ),
        migrations.CreateModel(
            name='FeedUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeds_type', models.CharField(choices=[('Layers Mash', 'Layers Mash'), ('Broilers Mash', 'Broilers Mash'), ('Starter', 'Starter'), ('Finisher', 'Finisher')], max_length=200, null=True)),
                ('feed_quantity_used', models.FloatField(null=True)),
                ('feed_usage_date', models.DateField(auto_now_add=True, null=True)),
                ('brooder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.brooder')),
                ('flock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.flock')),
            ],
        ),
    ]
