# Generated by Django 3.2.8 on 2021-11-08 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20211108_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_cost', models.FloatField(null=True)),
                ('sale_date', models.DateField(auto_now_add=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.order')),
            ],
        ),
        migrations.RenameModel(
            old_name='Feeds',
            new_name='Feed',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
