# Generated by Django 3.2.8 on 2021-11-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_medicine_medicine_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='billing_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_accepted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
