# Generated by Django 3.2.8 on 2021-11-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_sale_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='date_feed_bought',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
