# Generated by Django 3.2.8 on 2021-11-13 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20211113_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_date', models.DateField(auto_now_add=True, null=True)),
                ('vaccination_description', models.TextField(null=True)),
                ('flock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.flock')),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.medicine')),
            ],
        ),
    ]
