# Generated by Django 3.2.8 on 2021-11-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20211113_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='brooder',
            name='brooder_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
