# Generated by Django 3.2.8 on 2021-11-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_brooder_brooder_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='date_med_bought',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='last_used',
            field=models.DateField(blank=True, null=True),
        ),
    ]
