# Generated by Django 3.2.8 on 2021-11-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20211113_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='last_used',
        ),
    ]
