# Generated by Django 3.2.8 on 2021-11-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_medicine_last_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_created',
            new_name='date_added',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='feed_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flock',
            name='flock_breedtype',
            field=models.CharField(choices=[('Broiler', 'Broiler'), ('Layers', 'Layers')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
