# Generated by Django 3.2.8 on 2021-11-15 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20211114_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedusage',
            name='feeds_type',
        ),
        migrations.AddField(
            model_name='feedusage',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.feed'),
        ),
    ]
