# Generated by Django 3.2.8 on 2021-11-17 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20211115_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedusage',
            name='feed_quantity_used',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
