# Generated by Django 3.2.8 on 2021-11-25 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_feed_feed_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flock',
            name='flock_quantity',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
