# Generated by Django 3.2.8 on 2021-12-02 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20211201_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.order'),
        ),
    ]
