# Generated by Django 3.2.8 on 2021-12-02 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_sale_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.order'),
        ),
    ]
