# Generated by Django 3.2.8 on 2021-12-02 03:18

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_sale_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='id',
        ),
        migrations.AlterField(
            model_name='sale',
            name='order',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.order'),
        ),
    ]
