# Generated by Django 3.2.8 on 2021-12-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20211202_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='billing_status',
            field=models.CharField(choices=[('Not Billed', 'Not Billed'), ('Billed', 'Billed')], max_length=100, null=True),
        ),
    ]
