# Generated by Django 3.2.8 on 2021-12-02 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_sale_billing_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid',
            new_name='is_paid',
        ),
    ]
