# Generated by Django 3.2.8 on 2021-12-02 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_rename_order_cost_sale_order_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
