# Generated by Django 3.2.8 on 2021-12-05 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_alter_order_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='order',
        ),
    ]
