# Generated by Django 3.2.8 on 2021-12-10 04:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_remove_delivery_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_income', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('income_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.order')),
            ],
        ),
    ]
