# Generated by Django 3.2.8 on 2021-12-10 04:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_desc', models.CharField(max_length=100, null=True)),
                ('expense_amount', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('expense_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
